config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :index, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)

      user_path(current_user.id)

  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:book_create] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end

  end

  def show
    @book_create = Book.new
    @book = Book.find(params[:id])

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to "/books"
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:book_update] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new

  end

  def index
    @users = User.all
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      @user = current_user
      redirect_to user_path(@user.id)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:user_update] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_create.html.erb
<h2 class = "mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>

  <div class = "form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>

  <div class = "form-group">
    <%= f.label :opinion, 'Opinion' %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class = "form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/books/_book_edit.html.erb
<h2 class = "mt-3">New book</h2>
<%= form_with model: @book, local:true do |f| %>

  <div class = "form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form_control book_title' %>
  </div>

  <div class = "form-group">
    <%= f.label :opinion, 'Opinion' %>
    <%= f.text_area :body, class: 'form_control book_body' %>
  </div>

  <div class = "form-group">
    <%= f.submit 'Create Book' %>
  </div>

<% end %>

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <div id = "error_explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <%= form_with model:@book, local:true do |f| %>
        <div class = "form-group">
          <%= f.label :title, 'Title' %>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class = "form-group">
          <%= f.label :opinion, 'Opinion' %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class = "form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", '/books' %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class = "container px-5 px-sm-0">
  <div id = "error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/profile', user: current_user %>
      <%= render 'books/book_create', book: @book %>
    </div>

  <div class = "col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class = "table table-hover table-inverse">

      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan = "3"></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "img/no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>

  </div>
</div>

app/views/books/show.html.erb
<%= flash[:book_create] %>
<%= flash[:book_update] %>

<div class = "container">
  <div class = "row">

    <div class = "col-md-3">
      <%= render 'users/profile', user: @book.user %>
      <%= render 'books/book_create', book: @book_create %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class = "table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "img/no_image.jpg" %>
                <br><%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to "Destroy", book_path, method: :delete, data: { confirm: "本当に消しますか？" }, class: 'btn btn-sm btn-danger' %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class = "container">
  <div class = "row">
    <h1 class = "px-3 mx-auto">
      Welcome to
      <i class = "fas fa-book">
      </i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class = "container">
    <div class = "row">
        <div class = "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

            <h1>
                welcome to
                <i class = "fas fa-book"></i>
                <strong>Bookers</strong> !!
            </h1>

            <p>
                In
                <i class = "fas fa-book"></i>
                <strong>Bookers</strong> ,
            </p>

            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>

            <div class = "btn-wrapper col-10 mx-auto">
                <div class = "row">
                    <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
                </div>
                <div class = "row">
                    <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class = "container">
          <a class = "navbar-brand" href = "/">
            <span>Bookers</span>
          </a>
          <button class = "navbar-toggler collapsed" type = "button" data-toggle = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "false" aria-label = "Toggle navigation" >
            <span class = "navbar-toggler-icon"></span>
          </button>

          <div class = "navbar-collapse collapse" id = "navbarNavDropdown" style>
            <ul class = "navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li>
                  <%= link_to "Home",user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Users","/users", class: 'fas fa-users nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Books",books_path, class: 'fas fa-book-open nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Log out",destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
                </li>

              <% else %>
                <li>
                  <%= link_to "Home" ,root_path, class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "About", "/home/about", class: 'fas fa-link nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Sign up",new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Log in",new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>

    </header>

    <main>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </main>

    <footer>
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_profile.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: "img/no_image2.jpg" %>
<table class = "table">
  <tbody>
    <tr></tr>

    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>

    </tbody>
</table>

<div class = "row">
  <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' do %>

  <% end %>
</div>

app/views/users/_profile_edit.html.erb
<h2>User info</h2>
<!--ここにプロフィール画像-->
<table class = "table">
  <tbody>
    <tr></tr>

    <tr>
      <th>name</th>
      <th><!--ここにユーザー名--></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><!--ここに紹介文--></th>
    </tr>

    </tbody>
</table>

<div class = "row">
  <!--ここに編集へのリンク-->
</div>

app/views/users/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <div id = "error_explanation">
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <%= form_with model: @user, local:true do |f| %>
        <div class = "form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class = "form-group">
          <%= f.label :image, 'Image' %>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class = "form-group">
          <%= f.label :introduction, 'Introduction' %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class = "form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/profile', user: current_user %>
      <%= render 'books/book_create', book: @book %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class = "table">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan = "3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>

                  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "img/no_image.jpg" %>

              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/profile', user: @user %>
      <%= render 'books/book_create', book: @book %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class = "table table-hover-table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan = "3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "img/no_image.jpg" %>

                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>


  </div>
</div>